"""Try

Revision ID: 6ab2eea3543f
Revises: 07c0f39ad71f
Create Date: 2023-05-27 16:57:59.013818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab2eea3543f'
down_revision = '07c0f39ad71f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
